import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import News from "@/components/News";
import Footer from "@/components/Footer";
import { ToastContainer } from "react-toastify";
import logo from '../../public/images/logo.png'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BookNest || Borrow your book online",
  description: "Generated by create next app",
  icons:{
    icon:'/images/logo.png'
  }
};

export default function RootLayout({ children }) {
  return (
    <html
      style={{ backgroundColor: '#1C1B1F' }}
      // data-theme="luxury"
      // data-theme="light"
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col text-white-s">
        <ToastContainer />

        <Navbar></Navbar>
        {/* <News></News> */}
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
